[package]
name = "e2e-test"
autobins = false
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
wasi-pg-client = { path = "../../crates/pg-client" }
tracing-subscriber = { version = "0.3", optional = true }

[target.'cfg(target_os = "wasi")'.dependencies]
wasip3 = { workspace = true }

[features]
tracing = ["wasi-pg-client/tracing", "dep:tracing-subscriber"]

[lib]
crate-type = ["cdylib"]
path = "src/main.rs"
